import type { Metadata } from 'next';
import './globals.css';
import { MonitorSmartphone } from 'lucide-react';
import Link from 'next/link';
import { ShoppingCart } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,  //slot default for children
/*   ads, //slot for ads */
}: Readonly<{
  children: React.ReactNode;  
  ads: React.ReactNode; 
}>) {

  return (
    <html lang="en">
      <body>
        <main className="flex flex-col justify-between min-h-screen">
          <header className="fixed flex justify-between items-center shadow-xl bg-white px-20 w-full h-20 z-40">
            <div className="flex items-center gap-3">
              <Link href="/" className="font-bold text-2xl">
                <MonitorSmartphone />
                <h1>Digital Shop</h1>
              </Link>
            </div>
            <div>
              <ShoppingCart />
            </div>
          </header>
          <div className="px-20 mt-30">{children}</div>
          {/* <div className="my-10 mx-auto flex justify-center">{ads}</div>  */}
        </main> 
        <footer className="bg-black w-full h-10 text-white flex items-center justify-center">
          <p>&copy; 2025 JS with Behrouz. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
